### ISSUE TITLE
Not Showing Up in Config 

### ISSUE THREAD

**Issue by ChrisPvz2** [basketini-jones/lootdeck#204]
So i installed the mod and it will not show up in the Mod Config Menu.
![20211031220257_1](https://user-images.githubusercontent.com/78077997/139624068-e0c79bb2-ece2-4acb-84e7-e5f802f7fe81.jpg)

**Comment by basketini-jones** [comment]
The creator of Mod Config Menu recommends ensuring that you're on the latest version, and also restarting the game with all your mods installed just to be safe. Be sure you're using "Mod Config Menu - Continued" too, and not the original one by piber20. If none of those work, try reinstalling/verifying integrity of the game files.

We'll be testing things on our end to make sure it's not a problem with Loot Deck. Let us know if the issue gets fixed, or if it still persists after trying the tips above.

**Comment by ngregrichardson** [comment]
@ChrisPvz2 I'm going to close this for now as we haven't been able to reproduce it, if the problem persists after the fixes above, feel free to leave another comment.
