### ISSUE TITLE
Add missing duplicate effects to remaining cards

### ISSUE THREAD

**Issue by basketini-jones** [basketini-jones/lootdeck#339]
- [x] Ansuz: Grants the Compass effect for the floor.
- [x] Dice Shard: Opens all the doors in the room that you reset.
- [x] The Emperor: Turns all charmed enemies into champions.
- [x] The Fool: Necronomicon effect on room entry.
- [x] The Hanged Man: Fills in all holes in the room.
- [x] The Sun: Grants full mapping effects on the reset floor.

**Comment by ngregrichardson** [comment]
Done lmao u didn't link it (dumb)(
