### ISSUE TITLE
Investigate lag on items

### ISSUE THREAD

**Issue by ngregrichardson** [basketini-jones/lootdeck#359]
It was reported that one of our items tends to lag the game, so it should be investigated which one.

- We know that it's one of the items because removing the callbacks for them clears up the lag.
- It may be caused by a player loop because the lag increases with the number of players

**Comment by basketini-jones** [comment]
Items that iterate through all players on update:
- Counterfeit Penny (MC_POST_UPDATE)
- Left Hand (MC_POST_PICKUP_UPDATE)
- Poker Chip (MC_POST_PICKUP_UPDATE)
- Purple Heart (MC_POST_UPDATE)

Items that run on all players via MC_POST_PEFFECT_UPDATE or MC_POST_PLAYER_UPDATE, not necessary iterative:
- Player Card
- Curved Horn
- Cancer
- Broken Ankh
- AAA Battery

**Comment by basketini-jones** [comment]
Marking this as resolved for now as Floof has no issues since the latest patch!
