### ISSUE TITLE
Make Loot Card passives like birthright or polaroid for tainted isaac.

### ISSUE THREAD

**Issue by BadsyEdgecat** [basketini-jones/lootdeck#378]
tainted isaac, when using a trinket card, will have it added to his limited inventory, instead of becoming permanent like gulping actual trinkets. it would be nice if it didnt do that.

**Comment by BadsyEdgecat** [comment]
to clarify, this only happens if tainted isaac doesnt have 8/12 items yet. but if he does have a full list it already exists outside of the item list.

**Comment by basketini-jones** [comment]
This makes sense to me! 😮

**Comment by basketini-jones** [comment]
Apparently, making it a quest item doesn't prevent it from taking up space in Tainted Isaac's inventory. This seems to be a bug with adding items directly via AddCollectible(), and since direct manipulation of Tainted Isaac's inventory is impossible right now, this is sadly unfixable.
