### ISSUE TITLE
[BUG] Joker Loot Card creates an entirely separate second cycling item when used by tainted isaac

### ISSUE THREAD

**Issue by BadsyEdgecat** [basketini-jones/lootdeck#379]
For example, using The Joker on a devil deal thats cycling between brimstone and dark bum, and having it grab Dark Bum, caused it to generate a Dark Bum pickup that cycled to The Pact instead of Brimstone.

**Comment by basketini-jones** [comment]
Sadly, the API doesn't let us access cycling items on pedestals, so this is currently unfixable. Will be noted for the future though!
