### ISSUE TITLE
Blank Card + Car Battery should trigger the hardcoded double effects of Loot Cards

### ISSUE THREAD

**Issue by basketini-jones** [basketini-jones/lootdeck#382]
This can be done with UseFlags USE_MIMIC and USE_CARBATTERY

**Comment by basketini-jones** [comment]
i think we decided this wasnt possible or necessary idk

**Comment by ngregrichardson** [comment]
This was blocked because the USE_CARBATTERY was not being set on the USE_CARD callback on the double call, since it only technically applies to the Blank Card item. We would fix this in a future update if the flag is added.
